# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d0bd7344806fca6e50c0f77d10dbf85"
application_url = "https://gateway-referred-spanish-proposal.trycloudflare.com"
embedded = true
name = "functions"
handle = "functions-54"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gateway-referred-spanish-proposal.trycloudflare.com/auth/callback",
  "https://gateway-referred-spanish-proposal.trycloudflare.com/auth/shopify/callback",
  "https://gateway-referred-spanish-proposal.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "codeinspire-wishlist.myshopify.com"
automatically_update_urls_on_dev = true
